# Lesson notes: Advanced pandas

## combing series and dataframe
- `.concat()` - allows us to add together
- `.append()`
- `.merge()` - similar to SQL join
- `.join()`

In [17]:
import numpy as np
import pandas as pd

In [18]:
# .concat()
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },

)


df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },

)


df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"],
    },

)




frame = [df1, df2, df3]

result = pd.concat(frame, ignore_index=True)


result

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [19]:
result = pd.concat(frame, keys=['x', 'y', 'z'])
result

       A    B    C    D
x 0   A0   B0   C0   D0
  1   A1   B1   C1   D1
  2   A2   B2   C2   D2
  3   A3   B3   C3   D3
y 0   A4   B4   C4   D4
  1   A5   B5   C5   D5
  2   A6   B6   C6   D6
  3   A7   B7   C7   D7
z 0   A8   B8   C8   D8
  1   A9   B9   C9   D9
  2  A10  B10  C10  D10
  3  A11  B11  C11  D11

In [20]:
# allows extraction of the original df objects
result_y = result.loc[('y')]
result_y

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [21]:
df4 = pd.DataFrame(
    {
        "B": ["B2", "B3", "B6", "B7"],
        "D": ["D2", "D3", "D6", "D7"],
        "F": ["F2", "F3", "F6", "F7"],
    },
    index=[12, 13, 14, 15],
)

In [22]:
result = pd.concat([df1, df4], ignore_index=True)
result

     A   B    C   D    F
0   A0  B0   C0  D0  NaN
1   A1  B1   C1  D1  NaN
2   A2  B2   C2  D2  NaN
3   A3  B3   C3  D3  NaN
4  NaN  B2  NaN  D2   F2
5  NaN  B3  NaN  D3   F3
6  NaN  B6  NaN  D6   F6
7  NaN  B7  NaN  D7   F7

In [23]:
result = pd.concat([df1, df4], ignore_index=True, axis=1)
result

      0    1    2    3    4    5    6
0    A0   B0   C0   D0  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN
12  NaN  NaN  NaN  NaN   B2   D2   F2
13  NaN  NaN  NaN  NaN   B3   D3   F3
14  NaN  NaN  NaN  NaN   B6   D6   F6
15  NaN  NaN  NaN  NaN   B7   D7   F7

# pd.merge()

In [24]:
left_df = pd.DataFrame({'Courses': ["Spark","PySpark","Python","pandas","Java"],
                    'Fee' : [20000,25000,30000,24000,40000],
                    'Duration':['30day','40days','60days','55days','50days']})

right_df = pd.DataFrame({'Courses': ["Java","PySpark","Python","pandas","Hyperion","html"],
                    'Fee': [20000,25000,30000,24000,40000,4000],
                    'Percentage':['10%','20%','25%','20%','10%','50%']})

In [26]:
left_df

   Courses    Fee Duration
0    Spark  20000    30day
1  PySpark  25000   40days
2   Python  30000   60days
3   pandas  24000   55days
4     Java  40000   50days

In [28]:
right_df

    Courses    Fee Percentage
0      Java  20000        10%
1   PySpark  25000        20%
2    Python  30000        25%
3    pandas  24000        20%
4  Hyperion  40000        10%
5      html   4000        50%

In [30]:
marge = pd.merge(left_df, right_df)
marge

   Courses    Fee Duration Percentage
0  PySpark  25000   40days        20%
1   Python  30000   60days        25%
2   pandas  24000   55days        20%

In [32]:
marge = pd.merge(left_df, right_df, on='Courses')
marge

   Courses  Fee_x Duration  Fee_y Percentage
0  PySpark  25000   40days  25000        20%
1   Python  30000   60days  30000        25%
2   pandas  24000   55days  24000        20%
3     Java  40000   50days  20000        10%

In [33]:
left = pd.DataFrame({'A': [1, 2], 'B': [1,2]})


right = pd.DataFrame({'A': [4, 5, 6], 'B': [2, 2, 2]})

In [34]:
result = pd.merge(left, right, on='B', how='inner')
result

   A_x  B  A_y
0    2  2    4
1    2  2    5
2    2  2    6

In [37]:
result = pd.merge(left, right, on='B', how='inner', validate='one_to_many')
result

   A_x  B  A_y
0    2  2    4
1    2  2    5
2    2  2    6

In [38]:
sales_data = {
    'TransactionID': [1, 2, 3, 4, 5],
    'ProductID': [101, 102, 103, 101, 105],
    'StoreID': [1, 2, 1, 3, 2],
    'Quantity': [5, 3, 2, 4, 1],
    'Amount': [500.00, 300.00, 200.00, 400.00, 150.00]
}

products_data = {
    'ProductID': [101, 102, 103, 104, 105],
    'ProductName': ['Laptop', 'Headphones', 'Smartphone', 'Tablet', 'Monitor'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics']
}

In [41]:
sale_df = pd.DataFrame(sales_data)
prod_df = pd.DataFrame(products_data)

merged_df = pd.merge(sale_df, prod_df, on='ProductID', how='left')

merged_df

,TransactionID,ProductID,StoreID,Quantity,Amount,ProductName,Category
0,1,101,1,5,500.0,Laptop,Electronics
1,2,102,2,3,300.0,Headphones,Electronics
2,3,103,1,2,200.0,Smartphone,Electronics
3,4,101,3,4,400.0,Laptop,Electronics
4,5,105,2,1,150.0,Monitor,Electronics

### pd.join()

In [43]:
technologies = {
    'Courses':["Spark","PySpark","Python","pandas"],
    'Fee' :[20000,25000,22000,30000],
    'Duration':['30days','40days','35days','50days'],
              }
index_labels=['r1','r2','r3','r4']

technologies2 = {
    'Courses':["Spark","Java","Python","Go"],
    'Discount':[2000,2300,1200,2000]
              }
index_labels2=['r1','r6','r3','r5']

In [45]:
df1 = pd.DataFrame(technologies, index=index_labels)
df2 = pd.DataFrame(technologies2, index=index_labels2)

In [48]:
df3 = df1.join(df2, lsuffix='_left', rsuffix='_right', how='inner')
df3

   Courses_left    Fee Duration Courses_right  Discount
r1        Spark  20000   30days         Spark      2000
r3       Python  22000   35days        Python      1200

In [50]:
df3 = df1.join(df2, lsuffix='_left', rsuffix='_right')
df3

   Courses_left    Fee Duration Courses_right  Discount
r1        Spark  20000   30days         Spark    2000.0
r2      PySpark  25000   40days           NaN       NaN
r3       Python  22000   35days        Python    1200.0
r4       pandas  30000   50days           NaN       NaN

In [52]:
df3 = df1.join(df2, lsuffix='_left', rsuffix='_right', how='right')
df3

   Courses_left      Fee Duration Courses_right  Discount
r1        Spark  20000.0   30days         Spark      2000
r6          NaN      NaN      NaN          Java      2300
r3       Python  22000.0   35days        Python      1200
r5          NaN      NaN      NaN            Go      2000

In [55]:
df3 = df1.set_index('Courses').join(df2.set_index('Courses'), how='inner')
df3

           Fee Duration  Discount
Courses
Spark    20000   30days      2000
Python   22000   35days      1200

### grouping and aggregation
- `df(series).aggregate(func)`-