# Lesson notes: Advanced pandas

## combing series and dataframe
- `.concat()` - allows us to add together
- `.append()`
- `.merge()` - similar to SQL join
- `.join()`

In [100]:
import numpy as np
import pandas as pd
import datetime

In [3]:
# .concat()
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },

)


df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },

)


df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"],
    },

)




frame = [df1, df2, df3]

result = pd.concat(frame, ignore_index=True)


result

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [4]:
result = pd.concat(frame, keys=['x', 'y', 'z'])
result

       A    B    C    D
x 0   A0   B0   C0   D0
  1   A1   B1   C1   D1
  2   A2   B2   C2   D2
  3   A3   B3   C3   D3
y 0   A4   B4   C4   D4
  1   A5   B5   C5   D5
  2   A6   B6   C6   D6
  3   A7   B7   C7   D7
z 0   A8   B8   C8   D8
  1   A9   B9   C9   D9
  2  A10  B10  C10  D10
  3  A11  B11  C11  D11

In [5]:
# allows extraction of the original df objects
result_y = result.loc[('y')]
result_y

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [6]:
df4 = pd.DataFrame(
    {
        "B": ["B2", "B3", "B6", "B7"],
        "D": ["D2", "D3", "D6", "D7"],
        "F": ["F2", "F3", "F6", "F7"],
    },
    index=[12, 13, 14, 15],
)

In [7]:
result = pd.concat([df1, df4], ignore_index=True)
result

     A   B    C   D    F
0   A0  B0   C0  D0  NaN
1   A1  B1   C1  D1  NaN
2   A2  B2   C2  D2  NaN
3   A3  B3   C3  D3  NaN
4  NaN  B2  NaN  D2   F2
5  NaN  B3  NaN  D3   F3
6  NaN  B6  NaN  D6   F6
7  NaN  B7  NaN  D7   F7

In [8]:
result = pd.concat([df1, df4], ignore_index=True, axis=1)
result

      0    1    2    3    4    5    6
0    A0   B0   C0   D0  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN
12  NaN  NaN  NaN  NaN   B2   D2   F2
13  NaN  NaN  NaN  NaN   B3   D3   F3
14  NaN  NaN  NaN  NaN   B6   D6   F6
15  NaN  NaN  NaN  NaN   B7   D7   F7

# pd.merge()

In [9]:
left_df = pd.DataFrame({'Courses': ["Spark","PySpark","Python","pandas","Java"],
                    'Fee' : [20000,25000,30000,24000,40000],
                    'Duration':['30day','40days','60days','55days','50days']})

right_df = pd.DataFrame({'Courses': ["Java","PySpark","Python","pandas","Hyperion","html"],
                    'Fee': [20000,25000,30000,24000,40000,4000],
                    'Percentage':['10%','20%','25%','20%','10%','50%']})

In [10]:
left_df

   Courses    Fee Duration
0    Spark  20000    30day
1  PySpark  25000   40days
2   Python  30000   60days
3   pandas  24000   55days
4     Java  40000   50days

In [11]:
right_df

    Courses    Fee Percentage
0      Java  20000        10%
1   PySpark  25000        20%
2    Python  30000        25%
3    pandas  24000        20%
4  Hyperion  40000        10%
5      html   4000        50%

In [12]:
marge = pd.merge(left_df, right_df)
marge

   Courses    Fee Duration Percentage
0  PySpark  25000   40days        20%
1   Python  30000   60days        25%
2   pandas  24000   55days        20%

In [13]:
marge = pd.merge(left_df, right_df, on='Courses')
marge

   Courses  Fee_x Duration  Fee_y Percentage
0  PySpark  25000   40days  25000        20%
1   Python  30000   60days  30000        25%
2   pandas  24000   55days  24000        20%
3     Java  40000   50days  20000        10%

In [14]:
left = pd.DataFrame({'A': [1, 2], 'B': [1,2]})


right = pd.DataFrame({'A': [4, 5, 6], 'B': [2, 2, 2]})

In [15]:
result = pd.merge(left, right, on='B', how='inner')
result

   A_x  B  A_y
0    2  2    4
1    2  2    5
2    2  2    6

In [16]:
result = pd.merge(left, right, on='B', how='inner', validate='one_to_many')
result

   A_x  B  A_y
0    2  2    4
1    2  2    5
2    2  2    6

In [17]:
sales_data = {
    'TransactionID': [1, 2, 3, 4, 5],
    'ProductID': [101, 102, 103, 101, 105],
    'StoreID': [1, 2, 1, 3, 2],
    'Quantity': [5, 3, 2, 4, 1],
    'Amount': [500.00, 300.00, 200.00, 400.00, 150.00]
}

products_data = {
    'ProductID': [101, 102, 103, 104, 105],
    'ProductName': ['Laptop', 'Headphones', 'Smartphone', 'Tablet', 'Monitor'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics']
}

In [18]:
sale_df = pd.DataFrame(sales_data)
prod_df = pd.DataFrame(products_data)

merged_df = pd.merge(sale_df, prod_df, on='ProductID', how='left')

merged_df

,TransactionID,ProductID,StoreID,Quantity,Amount,ProductName,Category
0,1,101,1,5,500.0,Laptop,Electronics
1,2,102,2,3,300.0,Headphones,Electronics
2,3,103,1,2,200.0,Smartphone,Electronics
3,4,101,3,4,400.0,Laptop,Electronics
4,5,105,2,1,150.0,Monitor,Electronics

### pd.join()

In [19]:
technologies = {
    'Courses':["Spark","PySpark","Python","pandas"],
    'Fee' :[20000,25000,22000,30000],
    'Duration':['30days','40days','35days','50days'],
              }
index_labels=['r1','r2','r3','r4']

technologies2 = {
    'Courses':["Spark","Java","Python","Go"],
    'Discount':[2000,2300,1200,2000]
              }
index_labels2=['r1','r6','r3','r5']

In [20]:
df1 = pd.DataFrame(technologies, index=index_labels)
df2 = pd.DataFrame(technologies2, index=index_labels2)

In [21]:
df3 = df1.join(df2, lsuffix='_left', rsuffix='_right', how='inner')
df3

   Courses_left    Fee Duration Courses_right  Discount
r1        Spark  20000   30days         Spark      2000
r3       Python  22000   35days        Python      1200

In [22]:
df3 = df1.join(df2, lsuffix='_left', rsuffix='_right')
df3

   Courses_left    Fee Duration Courses_right  Discount
r1        Spark  20000   30days         Spark    2000.0
r2      PySpark  25000   40days           NaN       NaN
r3       Python  22000   35days        Python    1200.0
r4       pandas  30000   50days           NaN       NaN

In [23]:
df3 = df1.join(df2, lsuffix='_left', rsuffix='_right', how='right')
df3

   Courses_left      Fee Duration Courses_right  Discount
r1        Spark  20000.0   30days         Spark      2000
r6          NaN      NaN      NaN          Java      2300
r3       Python  22000.0   35days        Python      1200
r5          NaN      NaN      NaN            Go      2000

In [24]:
df3 = df1.set_index('Courses').join(df2.set_index('Courses'), how='inner')
df3

           Fee Duration  Discount
Courses
Spark    20000   30days      2000
Python   22000   35days      1200

### grouping and aggregation
- `df(series).aggregate(func)`-

In [25]:
lion = pd.read_csv('Data\zoo.csv')
lion

<>:1: SyntaxWarning: "\z" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\z"? A raw string is also an option.
<>:1: SyntaxWarning: "\z" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\z"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_21900\587537598.py:1: SyntaxWarning: "\z" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\z"? A raw string is also an option.
  lion = pd.read_csv('Data\zoo.csv')

      animal  uniq_id  water_need
0   elephant     1001         500
1   elephant     1002         600
2   elephant     1003         550
3      tiger     1004         300
4      tiger     1005         320
5      tiger     1006         330
6      tiger     1007         290
7      tiger     1008         310
8      zebra     1009         200
9      zebra     1010         220
10     zebra     1011         240
11     zebra     1012         230
12     zebra     1013         220
13     zebra     1014         100
14     zebra     1015          80
15      lion     1016         420
16      lion     1017         600
17      lion     1018         500
18      lion     1019         390
19  kangaroo     1020         410
20  kangaroo     1021         430
21  kangaroo     1022         410

In [26]:
lion.count()

animal        22
uniq_id       22
water_need    22
dtype: int64

In [27]:
print(lion[['animal']].count())

animal    22
dtype: int64

In [28]:
print(lion.animal.count())

22

In [29]:
lion[['water_need']].sum()

water_need    7650
dtype: int64

In [30]:
lion.sum()

animal        elephantelephantelephanttigertigertigertigerti...
uniq_id                                                   22253
water_need                                                 7650
dtype: object

In [31]:
lion[['water_need']].min()

water_need    80
dtype: int64

In [32]:
lion[['water_need']].max()

water_need    600
dtype: int64

In [33]:
lion[['water_need']].mean()

water_need    347.727273
dtype: float64

In [34]:
lion[['water_need']].median()

water_need    325.0
dtype: float64

In [35]:
lion[['water_need']].std().round(2)

water_need    147.55
dtype: float64

In [36]:
lion.groupby('animal').mean()

          uniq_id  water_need
animal
elephant   1002.0  550.000000
kangaroo   1021.0  416.666667
lion       1017.5  477.500000
tiger      1006.0  310.000000
zebra      1012.0  184.285714

In [37]:
lion.groupby('animal').mean()[['water_need']]

          water_need
animal
elephant  550.000000
kangaroo  416.666667
lion      477.500000
tiger     310.000000
zebra     184.285714

In [38]:
type(lion.groupby('animal').mean().water_need)

pandas.Series

In [39]:
lion.groupby('animal')['animal'].count()

animal
elephant    3
kangaroo    3
lion        4
tiger       5
zebra       7
Name: animal, dtype: int64

In [40]:
df = pd.read_csv('Data\student_scores.csv', parse_dates=['birth'])

<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_21900\611242246.py:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  df = pd.read_csv('Data\student_scores.csv', parse_dates=['birth'])

In [41]:
df.shape

(27, 8)

In [42]:
df.describe()

                 id                birth      score
count     27.000000                   27  27.000000
mean   10005.000000  2000-01-05 00:00:00  77.703704
min    10001.000000  2000-01-01 00:00:00  61.000000
25%    10003.000000  2000-01-03 00:00:00  67.000000
50%    10005.000000  2000-01-05 00:00:00  78.000000
75%    10007.000000  2000-01-07 00:00:00  89.000000
max    10009.000000  2000-01-09 00:00:00  96.000000
std        2.631174                  NaN  11.591823

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          27 non-null     int64
 1   first_name  27 non-null     str
 2   last_name   27 non-null     str
 3   birth       27 non-null     datetime64[us]
 4   gender      27 non-null     str
 5   class       27 non-null     str
 6   Subject     27 non-null     str
 7   score       27 non-null     int64
dtypes: datetime64[us](1), int64(2), str(5)
memory usage: 1.8 KB

In [44]:
it_group = df.groupby('first_name')
it_group.groups

{'Bob': [24, 25, 26], 'Frank': [9, 10, 11], 'Fred': [21, 22, 23], 'Jane': [3, 4, 5], 'Jennifer': [15, 16, 17], 'Jessica': [18, 19, 20], 'John': [0, 1, 2], 'Mike': [12, 13, 14], 'Sarah': [6, 7, 8]}

In [45]:
multi_g = df.groupby(['first_name', 'last_name'])
multi_g.groups

{('Bob', 'Lopez'): RangeIndex(start=24, stop=27, step=1),
 ('Frank', 'Brown'): RangeIndex(start=9, stop=12, step=1),
 ('Fred', 'Clark'): RangeIndex(start=21, stop=24, step=1),
 ('Jane', 'Smith'): RangeIndex(start=3, stop=6, step=1),
 ('Jennifer', 'Wilson'): RangeIndex(start=15, stop=18, step=1),
 ('Jessica', 'Garcia'): RangeIndex(start=18, stop=21, step=1),
 ('John', 'Doe'): RangeIndex(start=0, stop=3, step=1),
 ('Mike', 'Davis'): RangeIndex(start=12, stop=15, step=1),
 ('Sarah', 'Thomas'): RangeIndex(start=6, stop=9, step=1)}

In [46]:
# looping/iterating through groups
for name, group in it_group:
    print('{}'.format(name))
    print(group)

Bob
       id first_name last_name      birth gender class     Subject  score
24  10009        Bob     Lopez 2000-01-09      F     B    Calculus     91
25  10009        Bob     Lopez 2000-01-09      F     B    Geometry     81
26  10009        Bob     Lopez 2000-01-09      F     B  Statistics     75
Frank
       id first_name last_name      birth gender class     Subject  score
9   10004      Frank     Brown 2000-01-04      M     A    Calculus     88
10  10004      Frank     Brown 2000-01-04      M     A    Geometry     73
11  10004      Frank     Brown 2000-01-04      M     A  Statistics     86
Fred
       id first_name last_name      birth gender class     Subject  score
21  10008       Fred     Clark 2000-01-08      F     C    Calculus     66
22  10008       Fred     Clark 2000-01-08      F     C    Geometry     71
23  10008       Fred     Clark 2000-01-08      F     C  Statistics     94
Jane
      id first_name last_name      birth gender class     Subject  score
3  10002       Jane     Smith 2000-01-02      F     B    Calculus     63
4  10002       Jane     Smith 2000-01-02      F     B    Geometry     64
5  10002       Jane     Smith 2000-01-02      F     B  Statistics     94
Jennifer
       id first_name last_name      birth gender class     Subject  score
15  10006   Jennifer    Wilson 2000-01-06      M     C    Calculus     90
16  10006   Jennifer    Wilson 2000-01-06      M     C    Geometry     78
17  10006   Jennifer    Wilson 2000-01-06      M     C  Statistics     68
Jessica
       id first_name last_name      birth gender class     Subject  score
18  10007    Jessica    Garcia 2000-01-07      F     B    Calculus     70
19  10007    Jessica    Garcia 2000-01-07      F     B    Geometry     83
20  10007    Jessica    Garcia 2000-01-07      F     B  Statistics     80
John
      id first_name last_name      birth gender class     Subject  score
0  10001       John       Doe 2000-01-01      M     A    Calculus     63
1  10001       John       Doe 2000-01-01      M     A    Geometry     65
2  10001       John       Doe 2000-01-01      M     A  Statistics     63
Mike
       id first_name last_name      birth gender class     Subject  score
12  10005       Mike     Davis 2000-01-05      F     C    Calculus     94
13  10005       Mike     Davis 2000-01-05      F     C    Geometry     78
14  10005       Mike     Davis 2000-01-05      F     C  Statistics     90
Sarah
      id first_name last_name      birth gender class     Subject  score
6  10003      Sarah    Thomas 2000-01-03      M     B    Calculus     96
7  10003      Sarah    Thomas 2000-01-03      M     B    Geometry     73
8  10003      Sarah    Thomas 2000-01-03      M     B  Statistics     61

In [47]:
subjj = df.groupby('Subject')
subjj.groups

subjj.get_group('Calculus')

       id first_name last_name      birth gender class   Subject  score
0   10001       John       Doe 2000-01-01      M     A  Calculus     63
3   10002       Jane     Smith 2000-01-02      F     B  Calculus     63
6   10003      Sarah    Thomas 2000-01-03      M     B  Calculus     96
9   10004      Frank     Brown 2000-01-04      M     A  Calculus     88
12  10005       Mike     Davis 2000-01-05      F     C  Calculus     94
15  10006   Jennifer    Wilson 2000-01-06      M     C  Calculus     90
18  10007    Jessica    Garcia 2000-01-07      F     B  Calculus     70
21  10008       Fred     Clark 2000-01-08      F     C  Calculus     66
24  10009        Bob     Lopez 2000-01-09      F     B  Calculus     91

In [48]:
agg_group_mean = df.groupby('Subject')['score'].mean()
agg_group_mean

Subject
Calculus      80.111111
Geometry      74.000000
Statistics    79.000000
Name: score, dtype: float64

In [49]:
stud_mean = df.groupby(['first_name', 'last_name'])['score'].mean()
print(stud_mean)

first_name  last_name
Bob         Lopez        82.333333
Frank       Brown        82.333333
Fred        Clark        77.000000
Jane        Smith        73.666667
Jennifer    Wilson       78.666667
Jessica     Garcia       77.666667
John        Doe          63.666667
Mike        Davis        87.333333
Sarah       Thomas       76.666667
Name: score, dtype: float64

In [50]:
agg_group = df.groupby(['first_name', 'last_name'])['score'].agg([np.mean, np.sum, np.median])
agg_group

                           mean  sum  median
first_name last_name
Bob        Lopez      82.333333  247    81.0
Frank      Brown      82.333333  247    86.0
Fred       Clark      77.000000  231    71.0
Jane       Smith      73.666667  221    64.0
Jennifer   Wilson     78.666667  236    78.0
Jessica    Garcia     77.666667  233    80.0
John       Doe        63.666667  191    63.0
Mike       Davis      87.333333  262    90.0
Sarah      Thomas     76.666667  230    73.0

In [51]:
stud_count = df.groupby(['first_name', 'last_name'])['id'].count()
stud_count

first_name  last_name
Bob         Lopez        3
Frank       Brown        3
Fred        Clark        3
Jane        Smith        3
Jennifer    Wilson       3
Jessica     Garcia       3
John        Doe          3
Mike        Davis        3
Sarah       Thomas       3
Name: id, dtype: int64

## Transforming Data

In [52]:
fd = pd.read_csv('Data\sales_transactions.csv')
fd

<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\devon\AppData\Local\Temp\ipykernel_21900\1589639266.py:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  fd = pd.read_csv('Data\sales_transactions.csv')

    account           name  order       sku  quantity  unit price  ext price
0    383080       Will LLC  10001  B1-20000         7       33.69     235.83
1    383080       Will LLC  10001  S1-27722        11       21.12     232.32
2    383080       Will LLC  10001  B1-86481         3       35.99     107.97
3    412290  Jerde-Hilpert  10005  S1-06532        48       55.82    2679.36
4    412290  Jerde-Hilpert  10005  S1-82801        21       13.62     286.02
5    412290  Jerde-Hilpert  10005  S1-06532         9       92.55     832.95
6    412290  Jerde-Hilpert  10005  S1-47412        44       78.91    3472.04
7    412290  Jerde-Hilpert  10005  S1-27722        36       25.42     915.12
8    218895      Kulas Inc  10006  S1-27722        32       95.66    3061.12
9    218895      Kulas Inc  10006  B1-33087        23       22.55     518.65
10   218895      Kulas Inc  10006  B1-33364         3       72.30     216.90
11   218895      Kulas Inc  10006  B1-20000        -1       72.18     -72.18

In [53]:
order_total = fd.groupby('order')['ext price'].sum()
order_total

order
10001     576.12
10005    8185.49
10006    3724.49
Name: ext price, dtype: float64

In [65]:
fd['Order Total'] = fd.groupby('order')['ext price'].transform('sum')
fd

,account,name,order,sku,quantity,unit price,ext price,Order_Total,Percent of Order,Order Total
0,383080,Will LLC,10001,B1-20000,7,33.69,235.83,576.12,0.409342,576.12
1,383080,Will LLC,10001,S1-27722,11,21.12,232.32,576.12,0.403249,576.12
2,383080,Will LLC,10001,B1-86481,3,35.99,107.97,576.12,0.187409,576.12
3,412290,Jerde-Hilpert,10005,S1-06532,48,55.82,2679.36,8185.49,0.327330,8185.49
4,412290,Jerde-Hilpert,10005,S1-82801,21,13.62,286.02,8185.49,0.034942,8185.49
5,412290,Jerde-Hilpert,10005,S1-06532,9,92.55,832.95,8185.49,0.101759,8185.49
6,412290,Jerde-Hilpert,10005,S1-47412,44,78.91,3472.04,8185.49,0.424170,8185.49
7,412290,Jerde-Hilpert,10005,S1-27722,36,25.42,915.12,8185.49,0.111798,8185.49
8,218895,Kulas Inc,10006,S1-27722,32,95.66,3061.12,3724.49,0.821890,3724.49
9,218895,Kulas Inc,10006,B1-33087,23,22.55,518.65,3724.49,0.139254,3724.49
10,218895,Kulas Inc,10006,B1-33364,3,72.30,216.90,3724.49,0.058236,3724.49
11,218895,Kulas Inc,10006,B1-20000,-1,72.18,-72.18,3724.49,-0.019380,3724.49

In [67]:
fd['Percent of Order'] = fd['ext price'] / fd['Order Total']
fd

,account,name,order,sku,quantity,unit price,ext price,Order_Total,Percent of Order,Order Total
0,383080,Will LLC,10001,B1-20000,7,33.69,235.83,576.12,0.409342,576.12
1,383080,Will LLC,10001,S1-27722,11,21.12,232.32,576.12,0.403249,576.12
2,383080,Will LLC,10001,B1-86481,3,35.99,107.97,576.12,0.187409,576.12
3,412290,Jerde-Hilpert,10005,S1-06532,48,55.82,2679.36,8185.49,0.327330,8185.49
4,412290,Jerde-Hilpert,10005,S1-82801,21,13.62,286.02,8185.49,0.034942,8185.49
5,412290,Jerde-Hilpert,10005,S1-06532,9,92.55,832.95,8185.49,0.101759,8185.49
6,412290,Jerde-Hilpert,10005,S1-47412,44,78.91,3472.04,8185.49,0.424170,8185.49
7,412290,Jerde-Hilpert,10005,S1-27722,36,25.42,915.12,8185.49,0.111798,8185.49
8,218895,Kulas Inc,10006,S1-27722,32,95.66,3061.12,3724.49,0.821890,3724.49
9,218895,Kulas Inc,10006,B1-33087,23,22.55,518.65,3724.49,0.139254,3724.49
10,218895,Kulas Inc,10006,B1-33364,3,72.30,216.90,3724.49,0.058236,3724.49
11,218895,Kulas Inc,10006,B1-20000,-1,72.18,-72.18,3724.49,-0.019380,3724.49

In [69]:
np.random.seed(seed=13)

df = pd.DataFrame(data=np.random.normal(loc=70, scale=10, size=(7,3)),
           columns=('San Francisco', 'San Diego', 'Los Angeles'),
            index=['Mon', 'Tues', 'Wed', 'Thurs', 'Fri', 'Sat', 'Sun']
                 )

df =df.round()


df

       San Francisco  San Diego  Los Angeles
Mon             63.0       78.0         70.0
Tues            75.0       83.0         75.0
Wed             84.0       79.0         85.0
Thurs           60.0       62.0         57.0
Fri             76.0       68.0         79.0
Sat             73.0       71.0         92.0
Sun             76.0       70.0         60.0

In [71]:
df.diff()

       San Francisco  San Diego  Los Angeles
Mon              NaN        NaN          NaN
Tues            12.0        5.0          5.0
Wed              9.0       -4.0         10.0
Thurs          -24.0      -17.0        -28.0
Fri             16.0        6.0         22.0
Sat             -3.0        3.0         13.0
Sun              3.0       -1.0        -32.0

In [73]:
df.diff(periods=2)

       San Francisco  San Diego  Los Angeles
Mon              NaN        NaN          NaN
Tues             NaN        NaN          NaN
Wed             21.0        1.0         15.0
Thurs          -15.0      -21.0        -18.0
Fri             -8.0      -11.0         -6.0
Sat             13.0        9.0         35.0
Sun              0.0        2.0        -19.0

In [75]:
df = pd.DataFrame({'period': [1, 2, 3, 4, 5, 6, 7, 8],
                   'sales': [12, 14, 15, 15, 18, 20, 19, 24],
                   'returns': [2, 2, 3, 3, 5, 4, 4, 6]})

df

   period  sales  returns
0       1     12        2
1       2     14        2
2       3     15        3
3       4     15        3
4       5     18        5
5       6     20        4
6       7     19        4
7       8     24        6

In [85]:
df['sales_diff'] = df['sales'].diff()
df

   period  sales  returns  sales-diff  sales_diff
0       1     12        2         NaN         NaN
1       2     14        2         2.0         2.0
2       3     15        3         1.0         1.0
3       4     15        3         0.0         0.0
4       5     18        5         3.0         3.0
5       6     20        4         2.0         2.0
6       7     19        4        -1.0        -1.0
7       8     24        6         5.0         5.0

In [87]:
df[df['sales_diff'] < 2]

   period  sales  returns  sales-diff  sales_diff
2       3     15        3         1.0         1.0
3       4     15        3         0.0         0.0
6       7     19        4        -1.0        -1.0

In [89]:
data = {
    'Date': ['2022-01-01', '2022-01-01', '2022-01-02', '2022-01-02'],
    'Category': ['A', 'B', 'A', 'B'],
    'Value': [10, 20, 15, 25]
}

df = pd.DataFrame(data)
df

         Date Category  Value
0  2022-01-01        A     10
1  2022-01-01        B     20
2  2022-01-02        A     15
3  2022-01-02        B     25

In [92]:
pivot_df = df.pivot(index='Date', columns='Category', values='Value')
pivot_df

Category     A   B
Date
2022-01-01  10  20
2022-01-02  15  25

In [93]:
data = {'Name': ['Alice', 'Bob', 'Alice', 'Charlie'],
        'Fruit': ['Apple', 'Banana', 'Orange', 'Apple'],
        'Quantity': [3, 2, 1, 4]}

df = pd.DataFrame(data)
df

      Name   Fruit  Quantity
0    Alice   Apple         3
1      Bob  Banana         2
2    Alice  Orange         1
3  Charlie   Apple         4

In [95]:
pivoted_df = df.pivot(index='Name', columns='Fruit', values='Quantity')
pivoted_df

Fruit    Apple  Banana  Orange
Name
Alice      3.0     NaN     1.0
Bob        NaN     2.0     NaN
Charlie    4.0     NaN     NaN

In [99]:
df = pd.DataFrame({ 'course': ['CS2e1', 'C5201', 'CS201','DE659', 'DE659', 'DE659'],
                   'batch': [1, 2, 3, 1, 2, 3],
                    'instructor': ['xaviel', 'young', 'zachary','carla','wendy', 'allen'],
                    'grade': [88.7, 92, 95.2, 78.3, 96, 92.5]
                    }
                  )

# Display the original DataFrame
print("Original DataFrame:")
df

Original DataFrame:

  course  batch instructor  grade
0  CS2e1      1     xaviel   88.7
1  C5201      2      young   92.0
2  CS201      3    zachary   95.2
3  DE659      1      carla   78.3
4  DE659      2      wendy   96.0
5  DE659      3      allen   92.5

In [105]:
np.random.seed(42)
start_date = datetime.date(2022, 1, 1)
end_date = datetime.date(2022, 1, 10)
date_range = pd.date_range(start_date, end_date, freq='D')
# Create a DataFrame with daily returns for different stocks
data = {
    'Date': np.repeat(date_range, 3),
    'Stock': ['AAPL', 'GOOGL', 'MSFT'] * len(date_range),
    'Return': np.random.normal(loc=0.001, scale=0.01, size=len(date_range) * 3)
}

returns_df = pd.DataFrame(data)
returns_df

         Date  Stock    Return
0  2022-01-01   AAPL  0.005967
1  2022-01-01  GOOGL -0.000383
2  2022-01-01   MSFT  0.007477
3  2022-01-02   AAPL  0.016230
4  2022-01-02  GOOGL -0.001342
5  2022-01-02   MSFT -0.001341
6  2022-01-03   AAPL  0.016792
7  2022-01-03  GOOGL  0.008674
8  2022-01-03   MSFT -0.003695
9  2022-01-04   AAPL  0.006426
10 2022-01-04  GOOGL -0.003634
11 2022-01-04   MSFT -0.003657
12 2022-01-05   AAPL  0.003420
13 2022-01-05  GOOGL -0.018133
14 2022-01-05   MSFT -0.016249
15 2022-01-06   AAPL -0.004623
16 2022-01-06  GOOGL -0.009128
17 2022-01-06   MSFT  0.004142
18 2022-01-07   AAPL -0.008080
19 2022-01-07  GOOGL -0.013123
20 2022-01-07   MSFT  0.015656
21 2022-01-08   AAPL -0.001258
22 2022-01-08  GOOGL  0.001675
23 2022-01-08   MSFT -0.013247
24 2022-01-09   AAPL -0.004444
25 2022-01-09  GOOGL  0.002109
26 2022-01-09   MSFT -0.010510
27 2022-01-10   AAPL  0.004757
28 2022-01-10  GOOGL -0.005006
29 2022-01-10   MSFT -0.001917

In [106]:
pivot_df = returns_df.pivot(index='Date', columns='Stock', values='Return')
pivot_df.head()

Stock           AAPL     GOOGL      MSFT
Date
2022-01-01  0.005967 -0.000383  0.007477
2022-01-02  0.016230 -0.001342 -0.001341
2022-01-03  0.016792  0.008674 -0.003695
2022-01-04  0.006426 -0.003634 -0.003657
2022-01-05  0.003420 -0.018133 -0.016249